version: "3"
services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8078:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jupyter_server_config.json:/home/jovyan/.jupyter/jupyter_server_config.json
    # environment:
    #   - GRANT_SUDO=yes
    #   - NB_UID=1000
    #   - PASSWORD="1"
